# Generated by Django 3.0 on 2019-12-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=120)),
                ('apt', models.CharField(max_length=4)),
                ('email', models.CharField(max_length=60)),
                ('pwd', models.CharField(max_length=60)),
            ],
        ),
    ]
